### ISSUE TITLE
readme: be more concise

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/cubi-tools#13]
I just noticed that the short description of the `update_metadata` script unnecessarily introduces a new name, which makes its intent less clear: what are "metafiles"? They are metadata files, and to make it obvious what is meant by that, it could also mention an example like so: `...metadata files such as the license or citation info.`

A second point: the description speaks of workflows only, but all (!) CUBI repositories must be initialized with a license, citation info etc. (see the readme in the metadata files repo, it is quite clear about that).

**Comment by svenbioinf** [comment]
updated readme

**Comment by svenwillger** [comment]
Issue addressed by Sven B
