### ISSUE TITLE
use bool switch, not value

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/cubi-tools#16]
For True/False CLI switches, this is the way to do it:

```python
parser.add_argument(
   "--some-switch",
   "-s",
   action="store_true",
   default=False,
   dest="some_switch",
   help="This switches something on or off"
)
```

https://github.com/core-unit-bioinformatics/devtools/blob/0393e1701100d6c307d339253cad21f3a051d0ed/update_template.py#L61-L64

**Comment by svenbioinf** [comment]
Ofc I can change it according to your suggestion. Do you mind giving me more details on what advantages/disadvantages my solution has compared to yours?

**Comment by svenwillger** [comment]
Implemented
