### ISSUE TITLE
prefer single return over many

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/cubi-tools#24]
(Obviously, there is a mishap regarding the placement of the print statements)

Apart from that, scattered return statements like that are discouraged for functions that are not just simple `if/else` checks, and the whole function body could be simplified via some simple logic:
```
do_update = (local_sum != ref_sum) and user_wants_update(...)
if do_update:
    [ ... ]
else:
    [ ... ]
```
where the function `user_wants_update(...)` returns `True/False` depending on user input.

https://github.com/core-unit-bioinformatics/cubi-tools/blob/7929227c84bb10916943b960e7213cab597be43c/cubi-tools/update_metadata.py#L244-L250

**Comment by svenwillger** [comment]
Implemented
