### ISSUE TITLE
Parameter: --init-preset {github,githhu} not intuitive

### ISSUE THREAD

**Issue by svenbioinf** [core-unit-bioinformatics/cubi-tools#27]
https://github.com/core-unit-bioinformatics/cubi-tools/blob/9382cd705eadf5d6b0aa3d3eb2f41b1cd7da48c0/cubi-tools/auto_git.py#L91

With "github" I would expect an automatic git remote set up for github(only), however it is automatically set up for github and githhu.

Especially cause with "githhu" it sets up only a githhu remote (like expected).

Why not change to --init-preset {github,githhu,all}

**Comment by ptrebert** [comment]
fixed in 14140f6, changed behavior in v0.1
`all` is now essentially an alias for preset `github`
