### ISSUE TITLE
.identities documentation

### ISSUE THREAD

**Issue by svenbioinf** [core-unit-bioinformatics/cubi-tools#28]
https://github.com/core-unit-bioinformatics/cubi-tools/blob/9382cd705eadf5d6b0aa3d3eb2f41b1cd7da48c0/cubi-tools/auto_git.py#L111

Offer a definition or example of the required files in .identities.

**Comment by ptrebert** [comment]
updated readme in 51a70f0 - please check if that is clear now

**Comment by ptrebert** [comment]
updated cli help in 8098c3f w/ brief description and pointer to readme
