### ISSUE TITLE
add dryrun

### ISSUE THREAD

**Issue by svenbioinf** [core-unit-bioinformatics/cubi-tools#29]
https://github.com/core-unit-bioinformatics/cubi-tools/blob/9fa5240946666f1c4ebe27fd02ac28692b62bfe1/cubi-tools/update_metadata.py#L52

Add dryrun functionality and parameter

**Comment by svenwillger** [comment]
@ptrebert Is this really desired?

**Comment by svenwillger** [comment]
A dry run option has been added
