### ISSUE TITLE
metadata update incomplete

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/cubi-tools#30]
The `update_metadata.py` script copies the `CITATION.md` and then prints the following messages and does nothing ...

```bash
LICENSE checking...
.editorconfig checking...
pyproject.toml checking...
files_updated? True
Update metadata files version in pyproject.toml? (y/n)y
```

**Comment by svenwillger** [comment]
The script also prints `"{file} updated!" even if the file couldn't be found on the server side and nothing happened.
Revise the script to add a check if desired file exists and/or actually was copied.

**Comment by svenwillger** [comment]
All stated metadata files are getting updated with a message if the update occurs. The pyproject.toml is downloaded if missing and if present the metadata files version is updated and the rest of the pyproject.toml stays untouched
