### ISSUE TITLE
useless print statement - can never be reached

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/cubi-tools#36]
same again a few lines down; putting something after a return is pointless (as indicated by any proper IDE ...)

https://github.com/core-unit-bioinformatics/cubi-tools/blob/041731d1fa2c4b0d960000748185f9110410ff90/cubi-tools/update_workflow.py#L305

**Comment by svenwillger** [comment]
Saw that but due to inexperience assumed that was done on purpose by Sven B and approved by you.
Those statements have been removed.
