### ISSUE TITLE
message is still deceiving

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/cubi-tools#39]
https://github.com/core-unit-bioinformatics/cubi-tools/blob/c734424b5f929cae7f0b601e9290f434bb90ab5b/cubi-tools/update_metadata.py#L260

This message is still deceiving - it's a dry run, so nothing gets updated, why does it say "file X updated!"? It should say "would be updated" or similar.

**Comment by svenwillger** [comment]
This issue has been addressed
