### ISSUE TITLE
the exit function is not for scripts

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/cubi-tools#42]
The `exit()` call here is triggers a hard exit somewhere in the middle of the script and it is unclear why that is needed; interruptions in the control flow should be treated explicitly by raising exceptions and dealing with them. Second, the `exit()` function is only available if the `site` module is loaded, which can be omitted by the user via the `-S` switch (read the docs).

https://github.com/core-unit-bioinformatics/cubi-tools/blob/33c72d2ad41b229a870d67694c9088fef28e2a4a/cubi-tools/update_metadata.py#L187

**Comment by svenwillger** [comment]
I replaced the `exit()` call with raising an exception with information what went wrong.
