### ISSUE TITLE
use the shutil module (the pythonic way)

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/cubi-tools#43]
Solving a simple file copy via a subprocess call is quite "costly", although in this particular instance, that is negligible. Python offers direct calls for file copying etc via the `shutil` module, which is the better way of doing that.

https://github.com/core-unit-bioinformatics/cubi-tools/blob/33c72d2ad41b229a870d67694c9088fef28e2a4a/cubi-tools/update_metadata.py#L361-L365

**Comment by svenwillger** [comment]
`cp` has been replace with a command via a `shutil` call.
