### ISSUE TITLE
more concise return

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/cubi-tools#45]
Most favorite example of my CS 101 lecturer: never write "if X == A then True else False"

so, this piece should concisely read as follows:

```python
if not (answer in pos or answer in neg):
    print(f"That was a yes or no question, but you answered: {answer}")
    return user_response(question)
else:
    return answer in pos
```

https://github.com/core-unit-bioinformatics/cubi-tools/blob/33c72d2ad41b229a870d67694c9088fef28e2a4a/cubi-tools/update_metadata.py#L486-L490

One remark here (implementing that is at your own discretion; the CUBI team can answer yes or no ...): very good use of a recursive function call to give the user another opportunity at answering the question. You could add one more parameter to the function (say, `user_response(question, attempt=0)`) and increment that by one each time the function calls itself. Then, after a fixed number of attempts (whatever, 3 or so), you just raise an `RuntimeError` because the user is apparently not capable of answering `yes` or `no`.

**Comment by svenwillger** [comment]
I used your concise code and included a counter that stops the script after 3 failed attempts to enter an appropriate answer.
